#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 05 18:08:25 PDT 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 88da97a11f694c159c1b8e234a8f9af9 --incr --debug typical --relax --mt 8 -L gtwizard_ultrascale_v1_7_7 -L xil_defaultlib -L in_system_ibert_v1_0_10 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot gtwizard_ultrascale_0_example_top_sim_behav xil_defaultlib.gtwizard_ultrascale_0_example_top_sim xil_defaultlib.glbl -log elaborate.log"
xelab -wto 88da97a11f694c159c1b8e234a8f9af9 --incr --debug typical --relax --mt 8 -L gtwizard_ultrascale_v1_7_7 -L xil_defaultlib -L in_system_ibert_v1_0_10 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot gtwizard_ultrascale_0_example_top_sim_behav xil_defaultlib.gtwizard_ultrascale_0_example_top_sim xil_defaultlib.glbl -log elaborate.log

