#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 05 18:06:38 PDT 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim gtwizard_ultrascale_0_example_top_sim_behav -key {Behavioral:sim_1:Functional:gtwizard_ultrascale_0_example_top_sim} -tclbatch gtwizard_ultrascale_0_example_top_sim.tcl -view /net/top/homes/psiddire/ODMB/ODMBDevelopment/OpticalTests/kcu_gtwiz_quad227/gtwizard_ultrascale_0_ex/PRBS.wcfg -log simulate.log"
xsim gtwizard_ultrascale_0_example_top_sim_behav -key {Behavioral:sim_1:Functional:gtwizard_ultrascale_0_example_top_sim} -tclbatch gtwizard_ultrascale_0_example_top_sim.tcl -view /net/top/homes/psiddire/ODMB/ODMBDevelopment/OpticalTests/kcu_gtwiz_quad227/gtwizard_ultrascale_0_ex/PRBS.wcfg -log simulate.log

